services:
  alfresco:
    build:
      context: ./alfresco
      args:
        ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
        DB: postgres
        SOLR_COMMS: secret
    container_name: alfresco_repository
    mem_limit: 7488m
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.username=${DB_USERNAME}
        -Ddb.password=${DB_PASSWORD}
        -Ddb.driver=org.postgresql.Driver
        -Ddb.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}  
        -Dalfresco_user_store.adminpassword=209c6174da490caeb422f3fa5a7ae634
        -Dsystem.preferred.password.encoding=bcrypt10
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.port.ssl=8983
        -Dsolr.secureComms=secret
        -Dsolr.baseUrl=/solr
        -Dindex.subsystem.name=solr6
        -Dsolr.sharedSecret=uhcklrwts6  
        -Dalfresco.host=${SERVER_NAME}
        -Dalfresco.port=8080
        -Dapi-explorer.url=http://${SERVER_NAME}:8080/api-explorer
        -Dalfresco.protocol=http 
        -Dshare.host=${SERVER_NAME}
        -Dshare.port=8080
        -Dshare.protocol=http 
        -Daos.baseUrlOverwrite=http://${SERVER_NAME}/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Dmessaging.broker.username=admin
        -Dmessaging.broker.password=admin   
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false 
        -Dopencmis.server.override=true
        -Dopencmis.server.value=http://${SERVER_NAME}:8080
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dhttpclient.config.transform.connectionRequestTimeout=500000
        -DlocalTransform.ocr.url=http://transform-ocr:8090/
        -Dhttpclient.config.transform.socketTimeout=500000
        -Dhttpclient.config.transform.connectionTimeout=500000 
        -Dcsrf.filter.enabled=false
        -Dalfresco.restApi.basicAuthScheme=true
        -Dauthentication.protection.enabled=false
        -XX:+UseG1GC -XX:+UseStringDeduplication
        -Dgoogledocs.enabled=false  
        -Ddev.email.not.sent=true  
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    volumes:
      - alf-repo-data:/usr/local/tomcat/alf_data
      - alf-repo-logs:/usr/local/tomcat/logs

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
    container_name: alfresco_core_aio
    restart: on-failure
    mem_limit: 2048m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        -Dserver.tomcat.threads.max=12
        -Dserver.tomcat.threads.min=4
        -Dlogging.level.org.alfresco.transform.common.TransformerDebug=ERROR
        -Dlogging.level.org.alfresco.transform=ERROR
        -Dlogging.level.org.apache.fontbox.ttf=ERROR
        -Dlogging.level.org.apache.pdfbox.cos.COSDocument=ERROR
        -Dlogging.level.org.apache.pdfbox.pdfparser=ERROR
        -Dlogging.level.org.apache.pdfbox.filter.FlateFilter=ERROR
        -Dlogging.level.org.apache.pdfbox.pdmodel.font=ERROR
        -Dlogging.level.org.apache.pdfbox.pdmodel.font.PDSimpleFont=FATAL
        -Dlogging.level.org.apache.pdfbox.pdmodel.font.PDFont=FATAL
        -Dlogging.level.org.apache.pdfbox.pdmodel.font.PDCIDFont=FATAL

  share:
    build:
      context: ./share
      args:
        SHARE_TAG: ${SHARE_TAG}
        SERVER_NAME: ${SERVER_NAME}
        HTTP_PORT: 8080
    container_name: alfresco_share
    mem_limit: 1872m
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      CSRF_FILTER_REFERER: "http://localhost:8080/.*"
      CSRF_FILTER_ORIGIN: "http://localhost:8080"
      JAVA_OPTS: >-
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
    depends_on:
      alfresco:
        condition: service_healthy
    volumes:
      - alf-share-logs:/usr/local/tomcat/logs

  solr6:
    build:
      context: ./search
      args:
        SEARCH_TAG: ${SEARCH_CE_TAG}
        SOLR_HOSTNAME: solr6
        ALFRESCO_HOSTNAME: alfresco
        ALFRESCO_COMMS: secret
        CROSS_LOCALE: "true"
        DISABLE_CONTENT_INDEXING: "false"
    container_name: alfresco_search
    mem_limit: 3744m
    environment:
      SOLR_JAVA_MEM: "-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      #Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      #Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "alfresco_search"
      SOLR_SOLR_PORT: "8983"
      #Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      SOLR_OPTS: >-
        -XX:-UseLargePages
        -Dalfresco.secureComms.secret=uhcklrwts6
    depends_on:
      alfresco:
        condition: service_healthy
    volumes:
      - solr-data:/opt/alfresco-search-services/data

  activemq:
    image: alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
    container_name: alfresco_activemq
    mem_limit: 1g
    environment:
      ACTIVEMQ_ADMIN_LOGIN: ${ACTIVEMQ_ADMIN_LOGIN}
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
    volumes:
      - activemq-data:/opt/activemq/data

  transform-ocr:
    image: angelborroy/alfresco-tengine-ocr:2.0.0
    container_name: alfresco_transform_ocr
    mem_limit: 1536m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        -Dserver.tomcat.threads.max=4
        -Dserver.tomcat.threads.min=1

  # HTTP proxy to provide HTTP Default port access to services
  # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
  # proxy:
  #   image: nginx:stable-alpine
  #   container_name: alfresco_proxy
  #   mem_limit: 128m
  #   depends_on:
  #     - alfresco
  #     - solr6
  #     - share
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
  #   ports:
  #     - ${BIND_IP_NGINX:-0.0.0.0}:8080:8080

volumes:
  alf-repo-data:
  activemq-data:
  alf-repo-logs:
  alf-share-logs:
  solr-data:
